blank_issues_enabled: false
contact_links:
  - name: Questions & ideas
    url: https://github.com/hypeIT-GmbH/CleanDock/discussions
    about: Use Discussions for questions and ideas - Issues are for bugs and feature requests.
